version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
      - node_modules:/app/node_modules
      - storage:/app/storage
    environment:
      - RAILS_ENV=development
      - RAILS_MAX_THREADS=5
    command: >
      bash -c "bundle install &&
               bin/rails db:prepare &&
               rm -f tmp/pids/server.pid &&
               bin/rails server -b 0.0.0.0"

volumes:
  gem_cache:
  node_modules:
  storage:
