default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: /app/storage/development.sqlite3

test:
  <<: *default
  database: /app/storage/test.sqlite3

production:
  <<: *default
  database: /app/storage/production.sqlite3
