name: Ruby

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.3.0"]

    steps:
      - uses: actions/checkout@v4

      # Install Ruby manually for self-hosted runners
      - name: Install Ruby
        run: |
          curl -fsSL https://github.com/rbenv/ruby-build/archive/refs/heads/master.tar.gz | tar -xz
          PREFIX=/usr/local ./ruby-build-master/bin/ruby-build ${{ matrix.ruby-version }} $RUNNER_TOOL_CACHE/ruby-${{ matrix.ruby-version }}
          export PATH=$RUNNER_TOOL_CACHE/ruby-${{ matrix.ruby-version }}/bin:$PATH
          ruby --version

      # Set up Bundler and cache gems
      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      # Run tests
      - name: Run tests
        run: bundle exec rake
