name: Ruby_pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      sqlite:
        image: nouchka/sqlite3:latest
        ports:
          - 3306

    steps:
      - uses: actions/checkout@v4

      - name: Rubyのセットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true # インストールされたgemをキャッシュ

      - name: 依存関係のインストール
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: データベースのセットアップ
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: テストの実行
        run: bundle exec rspec

      - name: Rubocopの実行
        run: bundle exec rubocop || true
        # 最初はスタイルの問題でCIが失敗しないように "|| true" を追加

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Rubyのセットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: 依存関係のインストール
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Brakemanでコード分析
        run: |
          gem install brakeman
          brakeman -A -q -w2

      - name: Railsベストプラクティスのチェック
        run: |
          bundle exec rails_best_practices .

  # オプション: CDのためのデプロイジョブ
  # デプロイ準備ができたらコメントを外す
  # deploy:
  #   needs: [test, lint]
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #   - uses: actions/checkout@v4
  #
  #   - name: 本番環境へのデプロイ
  #     # ここにデプロイ手順を追加
  #     # これはHeroku、AWSなどへのデプロイになる可能性があります
  #     run: echo "ここでデプロイが行われます"
